export const MOVEMENT_TYPES = {
  PURCHASE_IN: "purchase_in",
  SALE_OUT: "sale_out",
  ADJUSTMENT: "adjustment",
  RETURN_IN: "return_in",
  RETURN_OUT: "return_out",
  TRANSFER_OUT: "transfer_out",
  TRANSFER_IN: "transfer_in",
  INITIAL: "initial",
};

export const MOVEMENT_DIRECTIONS = {
  IN: "in",
  OUT: "out",
};

export const ALERT_STATUSES = {
  ACTIVE: "active",
  RESOLVED: "resolved",
  ACKNOWLEDGED: "acknowledged",
};

export const MOVEMENT_DIRECTION_MAP = {
  [MOVEMENT_TYPES.PURCHASE_IN]: MOVEMENT_DIRECTIONS.IN,
  [MOVEMENT_TYPES.SALE_OUT]: MOVEMENT_DIRECTIONS.OUT,
  [MOVEMENT_TYPES.ADJUSTMENT]: null,
  [MOVEMENT_TYPES.RETURN_IN]: MOVEMENT_DIRECTIONS.IN,
  [MOVEMENT_TYPES.RETURN_OUT]: MOVEMENT_DIRECTIONS.OUT,
  [MOVEMENT_TYPES.TRANSFER_OUT]: MOVEMENT_DIRECTIONS.OUT,
  [MOVEMENT_TYPES.TRANSFER_IN]: MOVEMENT_DIRECTIONS.IN,
  [MOVEMENT_TYPES.INITIAL]: MOVEMENT_DIRECTIONS.IN,
};
